ECommerce.UI/Areas/Admin/Controllers/ShirtsController.cs
using Ecommerce.DAL;
using Ecommerce.Repo.Handler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.Configuration;
using Ecommerce.BLL.Handler;

namespace ECommerce.UI.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ShirtsController : Controller
    {

        EcommerceDBEntities context;
        CustomShirtHandler customShirtHandler;
        int PageSize;
        public ShirtsController()
        {
            context = new EcommerceDBEntities();
            PageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PageSize"]);
            customShirtHandler = new CustomShirtHandler(context);
        }
        // GET: Admin/Shirts
        public ActionResult Index(int page = 1)
        {
            var shirts = customShirtHandler.List.ToPagedList(page, PageSize);
            return View(shirts);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CustomShirt model)
        {
            model.IsActive = true;
            model.CreatedOn = DateTime.UtcNow;
            customShirtHandler.Add(model);
            return RedirectToAction("index");
        }

        public ActionResult Delete(long Id)
        {
            var shirt = customShirtHandler.FindById(Id);
            shirt.ModifiedOn = DateTime.UtcNow;
            customShirtHandler.Delete(shirt);
            return RedirectToAction("index");
        }
        [HttpGet]
        public ActionResult Edit(long Id)
        {
            var model = customShirtHandler.FindById(Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CustomShirt model)
        {
            var oldModel = customShirtHandler.FindById(model.Id);
            oldModel.Type = model.Type;
            oldModel.ShirtPrice = model.ShirtPrice;
            oldModel.FrontPrintPrice = model.FrontPrintPrice;
            oldModel.BackPrintPrice = model.BackPrintPrice;
            oldModel.ModifiedOn = DateTime.UtcNow;
            customShirtHandler.Update(oldModel);
            return RedirectToAction("index");
        }
    }
}

ECommerce.UI/Areas/Admin/Views/Shirts/Create.cshtml
@model Ecommerce.DAL.CustomShirt
@{
    ViewBag.Title = "Custom Shirt";
}

@using Ecommerce.DAL.Enums
@using (Html.BeginForm())
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Create Cutom Shirt</h4>
        </div>
        <div class="panel-body">
            <div class="col-sm-12">
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.Type, new { @class = "control-label"})
                    @Html.DropDownListFor(x => x.Type, EnumHelper.GetSelectList(typeof(ShirtType)), "Select Shirt Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Type)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.ShirtPrice, new { @class = "control-label" })
                    @Html.TextBoxFor(x => x.ShirtPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ShirtPrice)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.FrontPrintPrice, new { @class = "control-label" })
                    @Html.TextBoxFor(x => x.FrontPrintPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FrontPrintPrice)
                </div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.BackPrintPrice, new { @class = "control-label" })
                    @Html.TextBoxFor(x => x.BackPrintPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.BackPrintPrice)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.Size, new { @class = "control-label" })
                    @Html.DropDownListFor(x => x.Size, EnumHelper.GetSelectList(typeof(ShirtSizeType)), "Select Shirt Size", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Size)
                </div>
            </div>
        </div>

        <div class="panel-footer text-right">
            <div class="row">
                <div class="col-sm-12">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Cancel" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

ECommerce.UI/Areas/Admin/Views/Shirts/Edit.cshtml
@model Ecommerce.DAL.CustomShirt
@{
    ViewBag.Title = "Edit";
}

@using Ecommerce.DAL.Enums
@using (Html.BeginForm())
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Create Cutom Shirt</h4>
        </div>
        <div class="panel-body">
            <div class="col-sm-12">
                <div class="col-sm-4">
                    @Html.HiddenFor(x => x.Id)
                    @Html.LabelFor(x => x.Type, new { @class = "control-label", @for = "Heading" })
                    @Html.DropDownListFor(x => x.Type, EnumHelper.GetSelectList(typeof(ShirtType)), "Select Shirt Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Type)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.ShirtPrice, new { @class = "control-label", @for = "Description" })
                    @Html.TextBoxFor(x => x.ShirtPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ShirtPrice)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.FrontPrintPrice, new { @class = "control-label", @for = "AnimationType" })
                    @Html.TextBoxFor(x => x.FrontPrintPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FrontPrintPrice)
                </div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.BackPrintPrice, new { @class = "control-label", @for = "AnimationType" })
                    @Html.TextBoxFor(x => x.BackPrintPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.BackPrintPrice)
                </div>
                <div class="col-sm-4">
                    @Html.LabelFor(x => x.Size, new { @class = "control-label" })
                    @Html.DropDownListFor(x => x.Size, EnumHelper.GetSelectList(typeof(ShirtSizeType)), "Select Shirt Size", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Size)
                </div>
            </div>
        </div>

        <div class="panel-footer text-right">
            <div class="row">
                <div class="col-sm-12">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <a href="@Url.Action("Index","Shirts")"  class="btn btn-primary" >Cancel</a>
                </div>
            </div>
        </div>
    </div>
}

ECommerce.UI/Areas/Admin/Views/Shirts/Index.cshtml
@model IEnumerable<Ecommerce.DAL.CustomShirt>
@{
    ViewBag.Title = "Custom Shirts";
    int i = 0;
}
@using Ecommerce.DAL.Enums
@using PagedList
@using PagedList.Mvc

<div class="panel panel-primary">
    <div class="panel-heading">

        <h4>Cutom Shirts</h4>
        <div class="pull-right">
            <a href="@Url.Action("Create", "Shirts", new { area="admin"})" class="btn btn-success">Create New</a>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Shirt Price</th>
                        <th>Front Price</th>
                        <th>Back Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Count() > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @switch (item.Type)
                                    {
                                        case (int)ShirtType.ShortSleeveRound:
                                            <label>Short Sleeve Round Neck</label>
                                            break;
                                        case (int)ShirtType.ShortSleeveV:
                                            <label>Short Sleeve V Neck</label>
                                            break;
                                        @*case (int)ShirtType.LongSleeveV:
                                            <label>Long Sleeve V Neck</label>
                                            break;
                                        case (int)ShirtType.LongSleeveRound:
                                            <label>Long Sleeve Round Neck</label>
                                            break;*@
                                        default:
                                            break;
                                    }
                                </td>
                                <td>@item.ShirtPrice</td>
                                <td>@item.FrontPrintPrice</td>
                                <td>@item.BackPrintPrice</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", "Shirts", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                                    @Html.ActionLink("Delete", "Delete", "Shirts", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="text-danger text-center">
                                No Record found.
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("index", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>