ECommerce.UI/Areas/Admin/Controllers/BannerController.cs
using Ecommerce.DAL;
using Ecommerce.Repo.Handler;
using ECommerce.UI.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ECommerce.UI.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class BannerController : Controller
    {
        EcommerceDBEntities context;
        BannerHandler BannerHandler;

        public BannerController()
        {
            context = new EcommerceDBEntities();
            BannerHandler = new BannerHandler(context);
        }
        // GET: Admin/Banner
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult CreateBanner()
        {
            return PartialView("_CreatePartial");
        }
        public ActionResult Save(Banner model, HttpPostedFileBase BannerImage)
        {
            if (BannerImage != null)
            {
                string FileUrl = FileManager.SaveImage(BannerImage);
                model.ImgUrl = FileUrl;
            }
            model.CreatedOn = DateTime.UtcNow;
            model.IsActive = true;
            BannerHandler.Add(model);
            return RedirectToAction("index");
        }
        public PartialViewResult Edit(long id)
        {
            Banner banner = BannerHandler.FindById(id);
            return PartialView("_EditPartial", banner);
        }
        public ActionResult Update(long id,Banner model, HttpPostedFileBase BannerImage)
        {
            Banner oldBanner = BannerHandler.FindById(id);
            oldBanner.Heading = model.Heading;
            oldBanner.Description = model.Description;
            oldBanner.AnimationType = model.AnimationType;
            if (BannerImage != null)
            {
                string FileUrl = FileManager.SaveImage(BannerImage);
                oldBanner.ImgUrl = FileUrl;
            }
            BannerHandler.Update(oldBanner);
            return RedirectToAction("index");
        }
        public PartialViewResult ListBanner()
        {
            var Banners = BannerHandler.List;
            return PartialView("_ListBannerPartial", Banners);
        }
        public ActionResult Delete(long id)
        {
            Banner Banner= BannerHandler.FindById(id);
            Banner.ModifedOn = DateTime.UtcNow;
            BannerHandler.Delete(Banner);
            return RedirectToAction("index");
        }
    }
}

ECommerce.UI/Areas/Admin/Views/Banner/Index.cshtml
<div id="crtbanner">
    @Html.Action("CreateBanner", "Banner")
</div>
@Html.Action("ListBanner", "Banner")

ECommerce.UI/Areas/Admin/Views/Banner/_CreatePartial.cshtml
@model Ecommerce.DAL.Banner
@using Ecommerce.DAL.Enums
<style>
    .fileinput-preview img{
        width:100%;
    }
</style>
@using (Html.BeginForm("Save", "Banner", FormMethod.Post, new { @class = "", @enctype = "multipart/form-data" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Create Banner</h4>
        </div>
        <div class="panel-body">
            <div class="col-sm-12">
                <div class="col-sm-3">
                    @Html.LabelFor(x => x.Heading, new { @class = "control-label", @for = "Heading" })
                    @Html.TextBoxFor(x => x.Heading, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x=>x.Heading)
                </div>
                <div class="col-sm-3">
                    @Html.LabelFor(x => x.Description, new { @class = "control-label", @for = "Description" })
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x=>x.Description)
                </div>
                <div class="col-sm-3">
                    @Html.LabelFor(x => x.AnimationType, new { @class = "control-label", @for = "AnimationType" })
                    @Html.DropDownListFor(x=>x.AnimationType,EnumHelper.GetSelectList(typeof(SliderAnimation)),"Animation Type",new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.AnimationType)
                </div>
            </div>
            
            <div class="col-sm-12">
                <div class="col-sm-9" style="margin-top:10px;">
                    <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%; height: 150px;">
                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 150px;">

                        </div>
                        <div>
                            <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" class="file" name="BannerImage"></span>
                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                        </div>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12" id="tbl">

                </div>
            </div>
        </div>

        <div class="panel-footer text-right">
            <div class="row">
                <div class="col-sm-12">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Cancel" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

ECommerce.UI/Areas/Admin/Views/Banner/_EditPartial.cshtml
@model Ecommerce.DAL.Banner
@using Ecommerce.DAL.Enums

<style>
    .fileinput-preview img {
        width: 100%;
    }
</style>
@using (Html.BeginForm("Update", "Banner", FormMethod.Post, new { @class = "", @enctype = "multipart/form-data" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Create Banner</h4>
        </div>
        <div class="panel-body">
            <div class="col-sm-12">
                <div class="col-sm-3">
                    @Html.HiddenFor(x => x.Id)
                    @Html.LabelFor(x => x.Heading, new { @class = "control-label", @for = "Heading" })
                    @Html.TextBoxFor(x => x.Heading, new { @class = "form-control" })
                </div>
                <div class="col-sm-3">
                    @Html.LabelFor(x => x.Description, new { @class = "control-label", @for = "Description" })
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                </div>
                <div class="col-sm-3">
                    @Html.LabelFor(x => x.AnimationType, new { @class = "control-label", @for = "AnimationType" })
                    @Html.DropDownListFor(x => x.AnimationType, EnumHelper.GetSelectList(typeof(SliderAnimation)), "Animation Type", new { @class = "form-control" })
                </div>
            </div>

            <div class="col-sm-12">
                <div class="col-sm-9" style="margin-top:10px;">
                    <div class="fileinput fileinput-new" data-provides="fileinput" style="width: 100%; height: 150px;">
                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 150px;">
                            <img src="@Url.Content(Model.ImgUrl)" />
                        </div>
                        <div>
                            <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><input type="file" class="file" name="BannerImage"></span>
                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                        </div>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12" id="tbl">

                </div>
            </div>
        </div>

        <div class="panel-footer text-right">
            <div class="row">
                <div class="col-sm-12">
                    <input type="submit" value="Save" class="btn btn-success" />
                    <input type="reset" value="Cancel" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

ECommerce.UI/Areas/Admin/Views/Banner/_ListBannerPartial.cshtml
@model IEnumerable<Ecommerce.DAL.Banner>
@using Ecommerce.DAL.Enums
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>Banner Images</h4>
                <div class="options">

                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Heading</th>
                                <th>Description</th>
                                <th>Animation Type</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                           @if (Model != null && Model.Count() > 0)
                                       {
                                           int i = 1;
                                           foreach (var item in Model)
                                           {
                                <tr>
                                    <td>@i</td>
                                    <td><img src="@item.ImgUrl" class="img-responsive" style="width:50px;height:50px"/></td>
                                    <td>@item.Heading</td>
                                    <td>@item.Description</td>
                                    <td>
                                        @switch (item.AnimationType)
                                        {
                                            case (int)SliderAnimation.flipInX:
                                                <label>flipInX</label>
                                                break;
                                            case (int)SliderAnimation.fadeInUp:
                                                <label>fadeInUp</label>
                                                break;
                                            case (int)SliderAnimation.fadeInLeft:
                                                <label>fadeInLeft</label>
                                                break;
                                            case (int)SliderAnimation.fadeInDown:
                                                <label>fadeInDown</label>
                                                break;
                                        }
                                    </td>
                                    <td>
                                        @Ajax.ActionLink("Edit", "Edit", "Banner", new { id = item.Id },new AjaxOptions {HttpMethod="GET",UpdateTargetId= "crtbanner" }, new { @class = "btn btn-primary btn-sm" })
                                        @Html.ActionLink("Delete", "Delete", "Banner",new {id=item.Id }, new { @class = "btn btn-danger btn-sm" })
                                    </td>
                                </tr>
                                i++;
                                              }
                                          }
                                          else
                                          {
                            <tr>
                                <td colspan="6" class="text-danger text-center">
                                    No Record found.
                                </td>
                            </tr>
                           }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>