ECommerce.UI/Controllers/PayPalController.cs
using ECommerce.UI.Areas.Admin.Models;
using ECommerce.UI.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.UI.Controllers
{
    public class PayPalController : Controller
    {
        public ActionResult ValidateCommand(string product, string totalPrice, string quantity)
        {
            bool useSandbox = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSandbox"]);
            var paypal = new PayPalModel(useSandbox);

            paypal.item_name = product;
            paypal.amount = totalPrice;
            paypal.item_quantity = quantity;
            return View(paypal);
        }

        public ActionResult RedirectFromPaypal()
        {
            return View();
        }

        public ActionResult CancelFromPaypal()
        {
            return View();
        }

        public ActionResult NotifyFromPaypal()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

ECommerce.UI/Views/PayPal/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using (Html.BeginForm("ValidateCommand", "PayPal"))
{
    <div>
        <table>
            <tr>
                <td>
                    product Name:
                </td>
                <td>
                    <input type="text" name="product" value="Car" readonly />
                </td>
            </tr>
            <tr>
                <td>
                    Total Price:
                </td>
                <td>
                    $<input type="text" name="totalPrice" value="2500" readonly />
                </td>
            </tr>
            <tr>
                <td>
                    product quantity:
                </td>
                <td>
                    <input type="text" name="quantity" value="10" readonly />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="btnConfirm" value="Click here for payment with Paypal" />
                </td>
            </tr>
        </table>
    </div>
}  

ECommerce.UI/Views/PayPal/ValidateCommand.cshtml
@model ECommerce.UI.Models.PayPalModel
<body>
    <form id="hiddenform" action=@Model.actionURL>
        @Html.HiddenFor(model => model.cmd)
        @Html.HiddenFor(model => model.business)
        @Html.HiddenFor(model => model.no_shipping)
        @Html.HiddenFor(model => model.@return)
        @Html.HiddenFor(model => model.cancel_return)
        @Html.HiddenFor(model => model.notify_url)
        @Html.HiddenFor(model => model.currency_code)
        @Html.HiddenFor(model => model.item_name)
        @Html.HiddenFor(model => model.item_quantity)
        @Html.HiddenFor(model => model.amount)
    </form>
    <p style="text-align: center">
        <h3>
            Now you are connectin to the PayPal Application
        </h3>
    </p>
</body>
@Scripts.Render("~/bundles/jquery")

<script type="text/javascript" language="javascript">

    $(this.document).ready(function () {
        var form = $("form");
        form.submit();
    });
</script>  